# Generated by Django 2.1.15 on 2021-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependantPerson',
            fields=[
                ('rowid', models.IntegerField(db_column='RowID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=50, null=True)),
                ('dependantfullname', models.CharField(blank=True, db_column='DependantFullName', max_length=50, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('currentcity', models.CharField(blank=True, db_column='CurrentCity', max_length=250, null=True)),
                ('optionid', models.CharField(blank=True, db_column='OptionID', max_length=255, null=True)),
                ('locationtype', models.CharField(blank=True, db_column='LocationType', max_length=250, null=True)),
                ('vaccinationdate', models.DateTimeField(blank=True, db_column='VaccinationDate', null=True)),
                ('vaccinename', models.CharField(blank=True, db_column='VaccineName', max_length=50, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=255, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'DEPENDANT_PERSON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationOptions',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('optiontext', models.CharField(blank=True, db_column='OptionText', max_length=250, null=True)),
                ('questionid', models.CharField(blank=True, db_column='QuestionID', max_length=250, null=True)),
                ('locationtype', models.CharField(blank=True, db_column='LocationType', max_length=250, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=255, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'VACCINATION_OPTIONS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationSurvey',
            fields=[
                ('rowid', models.IntegerField(db_column='RowID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=50, null=True)),
                ('optionid', models.CharField(blank=True, db_column='OptionID', max_length=255, null=True)),
                ('locationtype', models.CharField(blank=True, db_column='LocationType', max_length=250, null=True)),
                ('vaccinationdate', models.DateTimeField(blank=True, db_column='VaccinationDate', null=True)),
                ('vaccinename', models.CharField(blank=True, db_column='VaccineName', max_length=50, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=255, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'VACCINATION_SURVEY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationSurveyLog',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('rowid', models.IntegerField(blank=True, db_column='RowID', null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=50, null=True)),
                ('optionid', models.CharField(blank=True, db_column='OptionID', max_length=255, null=True)),
                ('locationtype', models.CharField(blank=True, db_column='LocationType', max_length=250, null=True)),
                ('vaccinationdate', models.DateTimeField(blank=True, db_column='VaccinationDate', null=True)),
                ('vaccinename', models.CharField(blank=True, db_column='VaccineName', max_length=50, null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=255, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'VACCINATION_SURVEY_LOG',
                'managed': False,
            },
        ),
    ]
